apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfqap6517-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfqap6517-tenant-component
    app.kubernetes.io/part-of: loadfqap6517-tenant-app
  name: loadfqap6517-tenant-component
  namespace: loadfqap6517-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadfqap6517-tenant-component
    weight: null
status: {}
